ckeditor/static/ckeditor/ckeditor-init.js, ckeditor/templates/ckeditor/widget.html, ckeditor/widgets.py
In the django-ckeditor-updated fork I had contributed a way to add "External Plugin Resources" via a RichTextField parameter. Since this fork got merged, this did not work anymore. I've now adapted my changes to the new editor initialization approach based on ckeditor-init.js.
=> Restore external-plugin-resources handling.

ckeditor/widgets.py
Django 1.7 renamed django.forms.util to django.forms.utils. In order to silence the Deprecation warning a try-except block is needed.
=> Fix deprecation warning introduced in Django 1.7

README.rst
In current version it seems that loading the media is only related to widget documentation, which it isnt, I was really confused by this, custom section for media loading will make things more clear...
=> Loading form media section

ckeditor/forms.py, ckeditor/templates/browse.html, ckeditor/views.py
When django-ckeditor is used in a website with regular updates, frequently the image directory gets so crowded that it is rather difficult find a desired image in the gallery (often resulting in old images being uploaded again and again). Adding a simple search form to the browse() view solves this problem in great way.
=> add small image search field

README.rst, ckeditor_uploader/views.py, docs/INSTALL.md
I tried to add the image upload handling by ``_verify_file`` function, but for some reasons it was working as expected.
Now you can simply add ``CKEDITOR_ALLOW_NONIMAGE_FILES = False`` in the settings.py file and get an 'Invalid file' error if a non-image file is uploaded.
I also fixed a potential XSS threat by escaping the GET parameter which was directly used.
=> Changed non-image file upload behavior.

ckeditor_uploader/views.py
Modified the code in order to allocate a visible_filename to files, even if the 'CKEDITOR_IMAGE_BACKEND' is None. WIthout allocating a value to "visible_filename", you couldn't browse, with the search form, through the files because an error ('NoneType' object has no attribute 'lower') appear and make it crash.
French speaker here, sorry for my terrible english. Don't hesitate to ask me more explanations.
=> Update views.py for file browsing files

ckeditor_uploader/views.py
This change adds support for custom user models without `username` field when uploading image.
`username` field is not guaranteed in custom usermodels in django. 
Custom user models however can specify another field designated as a username via `USERNAME_FIELD`, whose value is always returned from `get_username()`
Should resolve issue #267 
`get_username()` is available in all supported versions of Django:
https://docs.djangoproject.com/en/1.8/topics/auth/customizing/#django.contrib.auth.models.AbstractBaseUser.get_username
=> Use username getter instead of accessing field directly

ckeditor_demo/demo_application/models.py, ckeditor_demo/urls.py, tox.ini
2082e001aa3151240ccba7477b695b76566070bb missed changing the `djangomaster` tox environment to `django110`.
This also fixes the failures for lint and isort.
=> Fix tox file to actually test Django 1.10

ckeditor/widgets.py, tox.ini
This enables the use of ManifestStaticFilesStorage and far-future expiry headers for staticfiles.
An excerpt from a site in production:
```
<script type="text/javascript" src="/static/admin/js/inlines.min.8ef8b2379896.js"></script>
<script type="text/javascript" src="/static/ckeditor/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="/static/ckeditor/ckeditor-init.js"></script>
<script type="text/javascript" src="/static/versatileimagefield/js/versatileimagefield.51787809ec9a.js"></script>
```
It would be great if ckeditor's files also had the hash in their filename.
Thanks!
=> CKEditorWidget: Go through static() so that the storage's URL generation is used

README.rst
`load staticfiles` isn't used anymore - 
https://docs.djangoproject.com/en/1.10/howto/static-files/
=> Change "load staticfiles" to "load static"

ckeditor/fields.py
Because django-ckeditor supports only Django 1.8+ and South is not compatible with these Django versions then we need to remove the south introspection rules.
This will also prevent some errors when upgrade from older versions of Django (pre 1.7) to new Django versions (1.9+) and South is still left in the environment.
=> Do not try to import south - it's unsuported

README.rst
`README.rst` documents how to avoid using `RichTextField` in your model if you want. However, it didn't document how to do avoid using `RichTextUploadingField`. This pull request fixes that.
It also includes a minor RST syntax fix. (You cannot put inline code literals within a bold sequence in RST.)
=> Document CKEditorUploadingWidget in README.rst

README.rst
Just fix documentation (include without url not working on Django 1.11).
Problem: http://stackoverflow.com/questions/38786461/django-error-your-url-pattern-is-invalid-ensure-that-urlpatterns-is-a-list-of
=> Updated README for CKEditor URL include

ckeditor_uploader/utils.py, ckeditor_uploader/views.py
Added setting for suppressing the date as well as the user in the uploads.  This allows for a single upload folder, if desired.  Sometimes, a client wants a single folder for uploads in the admin, especially if the total quantity of files is relatively small.  This allows for the same functionality as suppressing the user folder, only with the dates.
=> Added setting for suppressing the date as well as the user 

ckeditor_uploader/forms.py
This allows to clear out a search by submitting the empty form.
=> Do not require the q field in form

MANIFEST.in
modify MANIFEST.in to include ckeditor_uploader/static files.
#383
=> fix admin_base.css not found in package installed 

.travis.yml, AUTHORS.rst, CHANGELOG.rst, README.rst, setup.py
Currently, the RST is not formatted correctly on PyPI's website:
https://pypi.python.org/pypi/django-ckeditor/5.2.2
This pull request fixes the RST to make it work on the PyPI website. It fixed the errors that this command printed:
```
python setup.py check --restructuredtext --strict --metadata
```
=> Fix RST errors, for pretty display on PyPI

CHANGELOG.rst, README.rst, ckeditor/static/ckeditor/ckeditor-init.js, ckeditor/widgets.py, ckeditor_demo/demo_application/templates/form.html, ckeditor_demo/settings.py
This isn't very useful for the admin panel as Django always loads a jQuery instance there; but it's very useful when used on a website programmed without jQuery, or without jQuery readily available (such as when using webpack or something similar)
I did test the admin integration (both inline and no inline), and also external plugin support which I've documented in https://github.com/django-ckeditor/django-ckeditor/commit/4fba4699c45921e0fa07f68fed639a3e28923568
I did not test grappelli, but don't know why that wouldn't work as well.
=> Remove the jQuery requirement from ckeditor-init.js

ckeditor/widgets.py
This bug consists in following:
1. Django widgets are initialized on startup. It`s mean that for one RichTextField field will be created one CKEditorWidget widget on the startup. Every request to show this field on a form will use the same widget.
2. Method `CKEditorWidget.render()` is called every time the form displays. Another method 
`_set_config` is called inside: https://github.com/django-ckeditor/django-ckeditor/blob/master/ckeditor/widgets.py#L118
3. This method `_set_config` set the language in such way: if the language does not exist in attribute `config`, it takes language from `django.utils.translation.get_language`. BUT, if there is anything in `config['language']` - it does nothing (actually it leave the PREVIOUS language - it is the bug).
4. So, it turns out that if the …
=> Fix setting config language

ckeditor_uploader/views.py
A `TypeError` exception is raised during image uploading when `CKEDITOR_RESTRICT_BY_USER` is `True` because a bool value can not be passed to `getattr` function.
`  File "/home/pchinea/env/local/lib/python2.7/site-packages/ckeditor_uploader/views.py", line 28, in get_upload_filename
user_prop = getattr(user, RESTRICT_BY_USER)
TypeError: getattr(): attribute name must be string`
=> A TypeError Exception is raised when CKEDITOR_RESTRICT_BY_USER is True

ckeditor_uploader/views.py
- fixes issue #410 where browsing images broken while using a custom
upload prefix
- refactored user_path logic into separate function to use for upload and browse views
- browse still allows browsing all images if superuser
=> use same user path function for upload and browse

ckeditor/widgets.py
In Django 1.11, language identifiers for Simplified/Traditional Chinese are 'zh-hans' and 'zh-hant'.
In CKEditor, the keys to the two translations are 'zh-cn' and 'zh', respectively. If `django.utils.translation.get_language` returns `zh-hans`, CKEditor will render UI with translation of `zh` which is equivalent to `zh-hant` rather than `zh-hans`.
This patch converts the identifier between two conventions.
=> Convert Chinese language identifiers

README.rst
Primarily to fix the formatting of section [Required for using widget with file upload](https://github.com/django-ckeditor/django-ckeditor/blob/master/README.rst#required-for-using-widget-with-file-upload), particularly point number 2, which requires scrolling to be read (going beyond the right edge).
Corruption extends to [Read the Docs](https://django-ckeditor.readthedocs.io/en/latest/#required-for-using-widget-with-file-upload) and [PyPI](https://pypi.python.org/pypi/django-ckeditor/5.3.1#required-for-using-widget-with-file-upload) as well.
=> Fix formatting issues in README.rst

ckeditor_uploader/utils.py
These are working as expected for the time being
but raise deprecation warnings in Python 3.6
=> Fix invalid escape sequences in regexp patterns

ckeditor_uploader/views.py
If you use non-string properties of user object get_upload_filename will be failed. e.g. CKEDITOR_RESTRICT_BY_USER='id'
=> Added casting _get_user_path result to a string

README.rst
Refs #377 #382 
widgets.py now looks for CKEDITOR_BASEPATH value in settings, and defaults to `static('ckeditor/ckeditor/')`
References changes made to widgets.py on line 68. (https://github.com/django-ckeditor/django-ckeditor/blob/master/ckeditor/widgets.py#L68)
Also changes admin/base_site.html to admin/change_form.html because it
is more specific and is easier to extend.
=> Documentation for #377 'Automatically set CKEDITOR_BASEPATH'

README.rst
I've just added a note on how to render html content inside templates, for newcomers reading README file
=> Add template rendering example

ckeditor/widgets.py
Support for Widget.render() methods without the renderer argument is going to be removed in Django 2.1. This PR makes widget compatible with Django 2.1
=> Make widget compatible with Django 2.1

ckeditor_uploader/image/pillow_backend.py, ckeditor_uploader/utils.py, ckeditor_uploader/views.py
This is useful for allowing uploaded files to be in a different location than default storage. For instance, when used with django-storages, this allows for the default storage to be private (with querystring auth for S3) so that all files don't need to be public. But we can create a custom storage class for CKEditor uploads that is public so that anything uploaded will be accessible (useful if using ckeditor to send emails with).
I have tested with django-storages using s3 and local storage.
=> Allow for custom storage backends for uploader

README.rst
For compatibility with Django 2.1.
I got an exception without  `fields = '__all__' `.
`django.core.exceptions.ImproperlyConfigured: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is prohibited; form PostAdminForm needs updating.`
=> Modify widget sample in README

.travis.yml, ckeditor/widgets.py, ckeditor_demo/demo_application/tests.py, ckeditor_uploader/image/pillow_backend.py, ckeditor_uploader/views.py, tox.ini
I needed this lib for legacy project based on Django 1.9 and it didn't work. Here's the fix :slightly_smiling_face:
=> Fix regression - lib works again for Django 1.8--1.10. Cleanup tests.

ckeditor/static/ckeditor/ckeditor-init.js
Using the virtual machines that are provided by Microsoft for testing Internet Explorer (I've tested IE 9 and IE 10 on Windows 7), rich text fields never seem to be initialized properly.
From what I can tell, IE will set 'document.readyState' to 'interactive' even while the document is still loading.  As a result, the initialiseCKEditor function in ckeditor-init.js is invoked immediately.
* If the textarea itself has not yet been loaded at the time ckeditor-init.js is executed, initialiseCKEditor will never see it.
* If the textarea has been loaded, but 'ckeditor.js' hasn't yet been loaded, initialiseCKEditor will fail because CKEDITOR is undefined.  This is fixed by commit 9eb93f97d35ae589e9ca9b2628e3028a4cde1786.
With this change, combined with commit …
=> Fix initialization on old versions of Internet Explorer

ckeditor_uploader/backends/pillow_backend.py
Related to this issue: https://github.com/django-ckeditor/django-ckeditor/issues/550
After saving file by `self.storage_engine.save` self.file_object can be closed.
Trying to make thumbnail on closed file will raise and error.
As an back-end storage S3 was used.
=> Fix ValueError during creating thumbnail on closed file

ckeditor_uploader/templates/ckeditor/browse.html
I was getting an error in ckeditor uploader after clicking browse server. It seems that it is because Django 3 [doesn't accepts the template tag `staticfiles` anymore](https://stackoverflow.com/a/59381302/7373121), so it should be replace with ´static`.
I've tested this modification with Django 2.2 as well and it didn't break anything, so I think it ok.
=> fix template tag in uploader to work with Django 3

CHANGELOG.rst, ckeditor_uploader/forms.py
=> replace `ugettext_lazy` with `gettext_lazy` to get rid deprecation warning

ckeditor/static/ckeditor/ckeditor-init.js
Since django 1.9, adding an inline in the admin triggers the jQuery event "formset:added" ([docs](https://docs.djangoproject.com/en/3.1/ref/contrib/admin/javascript/)). Libraries that extend the django admin have adopted this convention, and likewise fire this event when adding an inline.
By calling the initialize function from an event listener for this event, we can ensure that django-ckeditor fields get replaced regardless of the mechanism (or the selector of the element) that adds formset inlines. This ensures compatibility with django-grappelli, django-polymorphic, and django-nested-admin. Merging this will fix theatlantic/django-nested-admin#175
=> Support django-nested-admin, django-polymorphic, and django-grappelli inlines

ckeditor_demo/urls.py, ckeditor_uploader/urls.py
This pull request is linked to issue #617 
Any doubt I will be available :)
=> Changing 'django.conf.urls.url()' to 'django.urls.re_path()' because of depreciation

README.rst, ckeditor_demo/demo_application/tests/test_custom_backend.py, ckeditor_demo/demo_application/tests/test_deprecation.py, ckeditor_demo/demo_application/tests/test_dummy.py, ckeditor_demo/demo_application/tests/tests_functional.py, ckeditor_demo/settings.py, ckeditor_uploader/backends/__init__.py, ckeditor_uploader/views.py
Addresses #686
Honours known `CKEDITOR_IMAGE_BACKEND` keys, while emitting deprecation warnings.
Any attempts to register custom backends will simply result in an import error.
If the approach is solid, needs a few new tests (and updates to existing tests) before merging.
=> Update CKEDITOR_IMAGE_BACKEND to fully qualified path

ckeditor/widgets.py
Currently, static("ckeditor/ckeditor") is called even with CKEDITOR_BASEPATH defined, which is unnecessary and messes up the functioning of s3manifestcollectstatic. This is a simple tweak to address that.
=> avoid calling static() at import if CKEDITOR_BASEPATH is defined

ckeditor/configs.py
We are using django-ckeditor but we found issue on the RichTextFiled
There is no any issue on big Screen Like Monitor greater than 21 inch but if we use smaller screen like Laptop or less than 15 inch monitor then there is issue of overlap with the django save button then i fixed it on our project and i want create pull request on your repo.
=> Fix the weight of the RichTextField (responsive)

ckeditor/static/ckeditor/ckeditor.css, ckeditor/widgets.py
- Fix #670
The source of the problem is that Django's styling overrides the background of some `<tr>` tags, so we could just override it with inherit.
https://github.com/django/django/blob/ddb6506618ea52c6b20e97eefad03ed847a1e3de/django/contrib/admin/static/admin/css/base.css#L344-L353
- Fix #741
The source of the problem is that Django defines both `color` and `background-color` properties, but ckeditor only overrides the `background-color`.
https://github.com/django/django/blob/ddb6506618ea52c6b20e97eefad03ed847a1e3de/django/contrib/admin/static/admin/css/base.css#L485-L493
https://github.com/ckeditor/ckeditor4/blob/64452216e7785997770214c483c01ac2750e1e0a/skins/moono-lisa/presets.css#L20-L30
=> Fix ckeditor with django dark theme
