django-ckeditor/django-ckeditor

ckeditor/widgets.py
Fix for show Links buttons in Full template config,
=> Links buttons not worked

ckeditor/widgets.py
Support for custom filebrowser.
=> Custom filebrowser url

ckeditor/utils.py
This correctly reimplement pull #168
=> Fixes #145 - Syntax Error on Python 3.2

ckeditor/widgets.py
STATIC_URL changed for static function
=> STATIC_URL changed

README.rst, ckeditor_uploader/templates/ckeditor/browse.html, ckeditor_uploader/views.py
While implementing the module into my site I figured it would be handy if the image browser displayed directories, as well as grouped the images so they don't show up as a big wall of thumbnails with no way of figuring out when they were uploaded and/or used. So I've developed this small feature - if enabled, the image browser now displays directories and thumbnails of images that belong to them, sorted by date.
Enabling the grouping requires setting the ``CKEDITOR_BROWSE_SHOW_DIRS`` to ``True``. My code iterates through the ``files`` list of dictionaries right before passing it to the template, and creates a set of unique directories out of images present in ``files``, then sorts it using the built-in ``sorted()`` function. 
``dir_list = sorted(set(os.path.dirname(f['src']) for f in …
=> Added optional directory display and image grouping to the image browser

ckeditor_uploader/templates/ckeditor/browse.html
Second commit just fixed my whitespace OCD.
=> override #container width. Closes #250

ckeditor/static/ckeditor/galleriffic/css/basic.css, ckeditor/static/ckeditor/galleriffic/css/galleriffic-2.css, ckeditor/static/ckeditor/galleriffic/css/galleriffic-5.css, ckeditor/static/ckeditor/galleriffic/js/jquery.galleriffic.js, ckeditor/static/ckeditor/galleriffic/js/jquery.history.js
From here:
https://github.com/iamvery/galleriffic
=> update galleriffic to 2.0.3

.travis.yml, ckeditor_uploader/image/dummy_backend.py, ckeditor_uploader/views.py
You'll need to set up the travis-ci webhook for this repository.
I've set it up on mine here:
https://travis-ci.org/nikolas/django-ckeditor
=> flake8 fixes + run flake8 automatically with travis

ckeditor_uploader/static/ckeditor/ckeditor_uploader/admin_base.css, ckeditor_uploader/templates/ckeditor/browse.html
=> remove dependency on django admin

README.rst
=> readme: grammar fix

README.rst
So it doesn't scroll off the page
=> README: fix plugin list

README.rst, ckeditor/static/ckeditor/ckeditor-basepath.js, ckeditor/static/ckeditor/ckeditor-init.js, ckeditor/templates/ckeditor/widget.html, ckeditor/widgets.py, ckeditor_demo/demo_application/templates/form.html
This would require reversing the order of `ckeditor-init.js` and `ckeditor.js`.
=> Automatically set CKEDITOR_BASEPATH

README.rst, ckeditor_uploader/views.py
Pretty minor change, just allows you to specify the upload folder prefix to be any property or callable on the user model.
=> allows uploads to be prefixed by any adhoc property on the user, not just the username

ckeditor/widgets.py
=> Reorder js assets in Media class of CKEditorWidget

.travis.yml, CHANGELOG.rst, ckeditor_demo/demo_application/templates/form.html, ckeditor_demo/demo_application/tests/test_deprecation.py, ckeditor_demo/settings.py, ckeditor_demo_requirements.txt, tox.ini
Run the tests with Django 3.0
Run the tests with Python 3.8
Replace `staticfiles` templatetags library usage with `static`
Add a templates validation step to the tests
=> Python3.8 & Django 3.0

CHANGELOG.rst, ckeditor/configs.py, ckeditor/widgets.py, ckeditor_demo/demo_application/forms.py, ckeditor_demo/demo_application/templates/form.html, ckeditor_demo/settings.py, ckeditor_uploader/templates/ckeditor/browse.html
- Move default settings to a configs.py file, so it can be imported while django apps aren't ready yet.
- Internationalize ckeditor_upload browse template
- Add ckeditor_upload features and custom configuration exemple to the demo
=> ckeditor_upload I18N , add ckeditor_upload to the demo

ckeditor/widgets.py
https://www.rfc-editor.org/rfc/bcp/bcp47.txt
```
Language subtag plus Script subtag:
zh-Hant (Chinese written using the Traditional Chinese script)
zh-Hans (Chinese written using the Simplified Chinese script)
```
=> add support for upcase language code

README.rst, ckeditor/widgets.py
=> Adds template name to CKEditorWidget and updates related documentation

ckeditor/fields.py, ckeditor/templates/ckeditor/widget.html, ckeditor/widgets.py, ckeditor_demo/demo_application/forms.py, ckeditor_demo/demo_application/tests/test_widget_context.py, ckeditor_demo/demo_application/tests/utils.py, ckeditor_demo/demo_application/views.py, ckeditor_demo/demo_application/widgets.py, ckeditor_demo/urls.py, ckeditor_uploader/fields.py
This resolves #706.
This PR also includes some other minor improvements - some necessary for the tests, others just for cleanup. See the commit messages for details.
=> Fix missing `widget` context variable

ckeditor/fields.py, ckeditor/widgets.py, ckeditor_demo/demo_application/forms.py, ckeditor_demo/demo_application/tests/test_fields.py, ckeditor_demo/demo_application/tests/test_widget_context.py, ckeditor_uploader/fields.py
This PR:
* adds some tests for model- and formfields in both standard forms and Django admin forms,
* fixes the failing multi-widget tests,
* and does a small refactor of the `ckeditor_uploader` fields.
=> Some test improvements

ckeditor/widgets.py
added the ability to change the template_name allowing the ability to create custom template widget html.
=> added template_name to init
